{"name": "test_form", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '#uploadPicture')).send keys\n\nReason: InvalidArgumentException: invalid argument: File not found : C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\file.txt\n  (Session info: chrome=128.0.6613.137)\nScreenshot: file://C:\\Users\\RMX\\.selene\\screenshots\\1757116022382\\1757116022382.png\nPageSource: file://C:\\Users\\RMX\\.selene\\screenshots\\1757116022382\\1757116022382.html", "trace": "fn = <selene.core.wait.Command object at 0x000001CA09130B90>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n                       ^^^^^^^^^^^^^^^\n\n.venv\\Lib\\site-packages\\selene\\core\\wait.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\selene\\core\\wait.py:61: in __call__\n    return self._fn(entity)\n           ^^^^^^^^^^^^^^^^\n.venv\\Lib\\site-packages\\selene\\core\\entity.py:469: in <lambda>\n    self.wait.command('send keys', lambda element: element().send_keys(*value))\n                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:304: in send_keys\n    self._execute(\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:573: in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001CA091A1940>\nresponse = {'status': 400, 'value': '{\"value\":{\"error\":\"invalid argument\",\"message\":\"invalid argument: File not found : C:\\\\\\\\Use...\\\\n#16 0x55fb114be013 \\\\u003Cunknown>\\\\n#17 0x55fb114cdebc \\\\u003Cunknown>\\\\n#18 0x7f76afd00ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\file.txt\nE         (Session info: chrome=128.0.6613.137)\nE       Stacktrace:\nE       #0 0x55fb114cf0ca <unknown>\nE       #1 0x55fb1119b2b0 <unknown>\nE       #2 0x55fb111e30e2 <unknown>\nE       #3 0x55fb1120f902 <unknown>\nE       #4 0x55fb111df2f9 <unknown>\nE       #5 0x55fb1120face <unknown>\nE       #6 0x55fb1122de26 <unknown>\nE       #7 0x55fb1120f6a3 <unknown>\nE       #8 0x55fb111dd4f3 <unknown>\nE       #9 0x55fb111de4fe <unknown>\nE       #10 0x55fb11495d7b <unknown>\nE       #11 0x55fb11499d31 <unknown>\nE       #12 0x55fb11481c85 <unknown>\nE       #13 0x55fb1149a8a2 <unknown>\nE       #14 0x55fb11466e1f <unknown>\nE       #15 0x55fb114bde48 <unknown>\nE       #16 0x55fb114be013 <unknown>\nE       #17 0x55fb114cdebc <unknown>\nE       #18 0x7f76afd00ac3 <unknown>\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:232: InvalidArgumentException\n\nDuring handling of the above exception, another exception occurred:\n\n    def test_form():\n        with allure.step('Открываем формум регистрации'):\n            file_path = os.path.join(os.path.dirname(__file__), 'file.txt')\n            browser.open('https://demoqa.com/automation-practice-form')\n        with allure.step('Заполнение формы'):\n            browser.element('#firstName').should(be.visible).type('Александр')\n            browser.element('#lastName').should(be.visible).type(\"Евдошенко\")\n            browser.element('#userEmail').should(be.blank).type('remix-92@mail.ru')\n            browser.all('[name=gender]').element_by(have.value('Male')).element('..').click()\n            browser.element('#userNumber').should(be.blank).type('8800200100')\n            browser.element('#dateOfBirthInput').click()\n            browser.element('.react-datepicker__month-select').type('May')\n            browser.element('.react-datepicker__year-select').type('1992')\n            browser.element('.react-datepicker__day--013').click()\n            browser.element('#subjectsInput').type('Computer Science').press_enter()\n            browser.all('.custom-checkbox').element_by(have.exact_text('Sports')).click()\n>           browser.element('#uploadPicture').send_keys(file_path)\n\ntest_main.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\selene\\core\\entity.py:469: in send_keys\n    self.wait.command('send keys', lambda element: element().send_keys(*value))\n.venv\\Lib\\site-packages\\selene\\core\\wait.py:161: in command\n    self.for_(Command(description, fn))\n.venv\\Lib\\site-packages\\selene\\core\\wait.py:150: in for_\n    return self._decorator(self)(logic)(fn)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfn = <selene.core.wait.Command object at 0x000001CA09130B90>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=getattr(reason, \"msg\", str(reason)),\n                    )\n                    # TODO: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    # TODO: should we have an option to turn on stacktrace logging?\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    # if it's a normal function, it should have __qualname__,\n                    # then use it, otherwise use str(fn)\n                    fn_name = getattr(\n                        fn,\n                        '__qualname__',\n                        getattr(fn, '__str__', lambda: str(fn))(),\n                    )\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn_name}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 4s, while waiting for:\nE                   browser.element(('css selector', '#uploadPicture')).send keys\nE                   \nE                   Reason: InvalidArgumentException: invalid argument: File not found : C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\file.txt\nE                     (Session info: chrome=128.0.6613.137)\nE                   Screenshot: file://C:\\Users\\RMX\\.selene\\screenshots\\1757116022382\\1757116022382.png\nE                   PageSource: file://C:\\Users\\RMX\\.selene\\screenshots\\1757116022382\\1757116022382.html\n\n.venv\\Lib\\site-packages\\selene\\core\\wait.py:148: TimeoutException"}, "steps": [{"name": "Открываем формум регистрации", "status": "passed", "start": 1757116029845, "stop": 1757116031834}, {"name": "Заполнение формы", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '#uploadPicture')).send keys\n\nReason: InvalidArgumentException: invalid argument: File not found : C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\file.txt\n  (Session info: chrome=128.0.6613.137)\nScreenshot: file://C:\\Users\\RMX\\.selene\\screenshots\\1757116022382\\1757116022382.png\nPageSource: file://C:\\Users\\RMX\\.selene\\screenshots\\1757116022382\\1757116022382.html\n\n", "trace": "  File \"C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\test_main.py\", line 24, in test_form\n    browser.element('#uploadPicture').send_keys(file_path)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\.venv\\Lib\\site-packages\\selene\\core\\entity.py\", line 469, in send_keys\n    self.wait.command('send keys', lambda element: element().send_keys(*value))\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\.venv\\Lib\\site-packages\\selene\\core\\wait.py\", line 161, in command\n    self.for_(Command(description, fn))\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\.venv\\Lib\\site-packages\\selene\\core\\wait.py\", line 150, in for_\n    return self._decorator(self)(logic)(fn)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^\n  File \"C:\\Users\\RMX\\PycharmProjects\\TEST_Jenkins\\.venv\\Lib\\site-packages\\selene\\core\\wait.py\", line 148, in logic\n    raise self._hook_failure(failure)\n"}, "start": 1757116031834, "stop": 1757116039599}], "start": 1757116029845, "stop": 1757116039629, "uuid": "ceed25f8-95d3-4b1c-82fb-1932d1db0bc6", "historyId": "c5f207a8ff8c456d4fc361ab1e7a086b", "testCaseId": "c5f207a8ff8c456d4fc361ab1e7a086b", "fullName": "test_main#test_form", "labels": [{"name": "suite", "value": "test_main"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "14068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_main"}], "titlePath": ["test_main.py"]}